name: 'Build & Test CshOverflow '
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Chesking out
      uses: actions/checkout@v2
    - name: Instaling .Net
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.200
        include-prerelease: false
    - name: Restoring paskage
      run: dotnet restore
    - name: Building Project
      run: dotnet build --no-restore
    - name: Testing Project
      run: dotnet test --no-build --verbosity normal
